# Default application configuration that all configurations inherit from.
script:
 - source ~/.rvm/scripts/rvm && rvm use 1.9.3   #this will activate ruby 1.9.3
 - ruby --version #ruby 1.9.3 is now ready to use

scss_files: "**/*.scss"
plugin_directories: ['.scss-linters']

# List of gem names to load custom linters from (make sure they are already
# installed)
plugin_gems: []

# Default severity of all linters.
severity: warning

linters:
  BangFormat:
    enabled: true
    space_before_bang: true
    space_after_bang: false

  BemDepth:
    enabled: false
    max_elements: 1

  BorderZero:
    enabled: true
    convention: zero # or `none`

  ChainedClasses:
    enabled: false

  ColorKeyword:
    enabled: true

  ColorVariable:
    enabled: true
    severity: error

  Comment:
    enabled: false
    style: silent

  DebugStatement:
    enabled: true
    severity: error

  DeclarationOrder:
    enabled: true
    severity: error

  DisableLinterReason:
    enabled: false

  DuplicateProperty:
    enabled: true
    severity: error

  ElsePlacement:
    enabled: true
    style: same_line # or 'new_line'
    severity: error

  EmptyLineBetweenBlocks:
    enabled: true
    ignore_single_line_blocks: true
    severity: error

  EmptyRule:
    enabled: true
    severity: error

  ExtendDirective:
    enabled: false

  FinalNewline:
    enabled: true
    present: true
    severity: error

  HexLength:
    enabled: true
    style: short # or 'long'
    severity: error

  HexNotation:
    enabled: true
    style: lowercase # or 'uppercase'
    severity: error

  HexValidation:
    enabled: true
    severity: error

  IdSelector:
    enabled: true
    severity: error

  ImportantRule:
    enabled: true
    severity: error

  ImportPath:
    enabled: false
    leading_underscore: false
    filename_extension: false

  Indentation:
    enabled: true
    allow_non_nested_indentation: false
    character: space # or 'tab'
    width: 4
    severity: error

  LeadingZero:
    enabled: true
    style: exclude_zero # or 'include_zero'
    severity: error

  MergeableSelector:
    enabled: true
    force_nesting: false
    severity: error

  NameFormat:
    enabled: false
    allow_leading_underscore: true
    convention: camel_lowercase # or 'hyphenated_lowercase', or 'snake_case', or a regex pattern

  NestingDepth:
    enabled: true
    max_depth: 3
    ignore_parent_selectors: true
    severity: error

  PlaceholderInExtend:
    enabled: true

  PrivateNamingConvention:
    enabled: false
    prefix: _

  PropertyCount:
    enabled: false
    include_nested: false
    max_properties: 10

  PropertySortOrder:
    enabled: false
    ignore_unspecified: false
    min_properties: 2
    separate_groups: false

  PropertySpelling:
    enabled: true
    extra_properties: []
    disabled_properties: []
    severity: error

  PropertyUnits:
    enabled: true
    global: [
      'ch', 'em', 'ex', 'rem',                 # Font-relative lengths
      'cm', 'in', 'mm', 'pc', 'pt', 'px', 'q', # Absolute lengths
      'vh', 'vw', 'vmin', 'vmax',              # Viewport-percentage lengths
      'deg', 'grad', 'rad', 'turn',            # Angle
      'ms', 's',                               # Duration
      'Hz', 'kHz',                             # Frequency
      'dpi', 'dpcm', 'dppx',                   # Resolution
      '%']                                     # Other
    properties: {
      font-size: ['rem', '%', 'vw', 'vh']
    }
    severity: error

  PseudoElement:
    enabled: true
    severity: error

  QualifyingElement:
    enabled: true
    allow_element_with_attribute: true
    allow_element_with_class: true
    allow_element_with_id: false
    severity: error

  SelectorDepth:
    enabled: true
    max_depth: 2
    severity: error

  SelectorFormat:
    enabled: false
    convention: hyphenated_lowercase # or 'strict_BEM', or 'hyphenated_BEM', or 'snake_case', or 'camel_case', or a regex pattern

  Shorthand:
    enabled: true
    allowed_shorthands: [1, 2, 3]
    severity: error

  SingleLinePerProperty:
    enabled: true
    allow_single_line_rule_sets: true
    severity: error

  SingleLinePerSelector:
    enabled: true
    severity: error

  SpaceAfterComma:
    enabled: true
    style: one_space # or 'no_space', or 'at_least_one_space'
    severity: error

  SpaceAfterPropertyColon:
    enabled: true
    style: one_space # or 'no_space', or 'at_least_one_space', or 'aligned'
    severity: error

  SpaceAfterPropertyName:
    enabled: true
    severity: error

  SpaceAfterVariableColon:
    enabled: false
    style: one_space # or 'no_space', 'at_least_one_space' or 'one_space_or_newline'
    severity: error

  SpaceAfterVariableName:
    enabled: true
    severity: error

  SpaceAroundOperator:
    enabled: true
    style: one_space # or 'at_least_one_space', or 'no_space'
    severity: error

  SpaceBeforeBrace:
    enabled: true
    style: space # or 'new_line'
    allow_single_line_padding: false
    severity: error

  SpaceBetweenParens:
    enabled: true
    spaces: 0
    severity: error

  StringQuotes:
    enabled: true
    style: single_quotes # or double_quotes
    severity: error

  TrailingSemicolon:
    enabled: true
    severity: error

  TrailingWhitespace:
    enabled: true
    severity: error

  TrailingZero:
    enabled: false
    severity: error

  TransitionAll:
    enabled: false

  UnnecessaryMantissa:
    enabled: true
    severity: error

  UnnecessaryParentReference:
    enabled: true

  UrlFormat:
    enabled: true

  UrlQuotes:
    enabled: true
    severity: error

  VariableForProperty:
    enabled: true
    properties: ['color', 'font-family']
    severity: error

  VendorPrefix:
    enabled: false
    identifier_list: base
    additional_identifiers: []
    excluded_identifiers: []

  ZeroUnit:
    enabled: true
    severity: error

  Compass::*:
    enabled: false
